# Generated by Django 6.0.6 on 2026-07-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='部门描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('status', models.CharField(choices=[('active', '在职'), ('left', '离职')], default='active', max_length=10, verbose_name='状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('annual', '年假'), ('sick', '病假'), ('personal', '事假'), ('other', '其他')], default='annual', max_length=10, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审批状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee', verbose_name='员工')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('level', models.CharField(blank=True, default='', max_length=20, verbose_name='职级')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.department', verbose_name='所属部门')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hr.position', verbose_name='职位'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='签到时间')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='签退时间')),
                ('type', models.CharField(choices=[('normal', '正常'), ('late', '迟到'), ('early', '早退'), ('absent', '缺勤')], default='normal', max_length=10, verbose_name='考勤类型')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee', verbose_name='员工')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='月份')),
                ('base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本工资')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='奖金')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='扣款')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='hr.employee', verbose_name='员工')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
